### ISSUE TITLE
Discovery message issue

### ISSUE THREAD

**Issue by Swamp-Ig** [Swamp-Ig/pizone#1]
Thanks for the efforts on this, but a few issues I have around the piece of code below

```python
def _discovery_recieved(self, data): 
    message = data.decode().split(',') 
    if len(message) < 4 or message[0] != 'ASPort_12107' or message[3] != 'iZone': 
        _LOG.warning("Invalid Message Received: %s", data.decode()) 
        return 
    if message[3] != 'iZone': 
        return
```

Mines failing as the return is only the 3 attributes and not returning 'iZone' as a 4th attribute which seems consistent with the interface spec

```
The controller sends: “IASD” to 255.255.255.255:12107

CB responds: “ASPort_PortNo,CB_ID,CB_IP”
```

**Comment by Swamp-Ig** [comment]
@gcondon1 was this your issue?

**Comment by Swamp-Ig** [comment]
This should be fixed in the v1.0.4 release.

**Comment by oompa01** [comment]
Discovery issue fixed and online! Did notice though that CONST zone is tied to the main power of the unit rather than a discrete zone.  On our system though the CONST is just treated as a default if no other zones are open.  This allows it to be turned on/off independently

**Comment by Swamp-Ig** [comment]
So what you're saying is that the const zone isn't controllable? Does it have sensors or anything? Is there any point in having it display in HA? 

Will close this issue, put a new one in with details if the const zone issue thing needs fixing.
