### ISSUE TITLE
Issue with unit not reporting FanAuto

### ISSUE THREAD

**Issue by Swamp-Ig** [Swamp-Ig/pizone#11]
See [comments](5#issuecomment-874589545) on #5 by @mikenye.

**Comment by Swamp-Ig** [comment]
@mike

**Comment by mikenye** [comment]
Thanks Penny, let me know if there's anything I can do to help.

**Comment by Swamp-Ig** [comment]
Try that update. If it works for you I'll release and update HA to match.

**Comment by Swamp-Ig** [comment]
Can this be closed now?

**Comment by Swamp-Ig** [comment]
No further updates, seems to be working
