### ISSUE TITLE
Unable to set target temperature in Home Assistant

### ISSUE THREAD

**Issue by Stog** [Swamp-Ig/pizone#20]
Hi,

Love this integration, it is great to see the work which has been put into it.

I am just having a bit of an issue in Home Assistant where I am unable to change the set_temperature for my system.

Looking through the code I can see when RAS = "Master" the CtrlZone needs to be 13 however mine seems to be set to 15 and after playing around within the config on the iZone controller I am unable to find a setting to make this 13.

I also have tried setting the RAS to the return air setting, which will then show the set temp but changes will not save to the controller when they are made in home assistant, and in iZone's infinite wisdom will then not show the current temp via the API.

Anyway, I was wondering if it would be possible to get an update made to allow CtrlZone 15 to have access to the set temperature feature or any other advice to get this working.

Cheers

`{
	"AirStreamDeviceUId":	"-",
	"DeviceType":	"ASH",
	"SysOn":	"off",
	"SysMode":	"cool",
	"SysFan":	"med",
	"SleepTimer":	0,
	"UnitType":	"Panasonic",
	"Supply":	"0.0",
	"Setpoint":	"25.0",
	"Temp":	"24.6",
	"RAS":	"master",
	"CtrlZone":	15,
	"Tag1":	"-",
	"Tag2":	"-",
	"Warnings":	"none",
	"ACError":	" OK",
	"Id":	0,
	"EcoLock":	"true",
	"EcoMax":	"30.0",
	"EcoMin":	"15.0",
	"NoOfConst":	1,
	"NoOfZones":	4,
	"SysType":	"310",
	"AirflowLock":	"onMin",
	"UnitLocked":	"false",
	"FreeAir":	"disabled",
	"FanAuto":	"disabled"
}`

**Comment by Swamp-Ig** [comment]
This is more of a HA issue really, I've got a [branch here](https://github.com/Swamp-Ig/home-assistant/tree/izone-master-fix) that probably will fix it, can you please test it?

**Comment by Stog** [comment]
Thank you. I will check it out and let you know.

**Comment by Stog** [comment]
Hi, I have gone through and tested your branch, it appears to be working perfectly for me.

Attached is a quick screen-capture showing the ability to now view and edit the target temperature.

https://user-images.githubusercontent.com/4464096/229786450-395fec1c-e8d7-4e5b-beb5-5e11b56c9c3c.mov

**Comment by Stog** [comment]
Sorry - just realised I closed this issue by accident when commenting.
